name: 'Semantic Release Action'
description: 'Use semantic-release to manage versions'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
outputs:
  version:
    description: 'The version released, if any.'
