name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  pre-release:
    name: Pre release
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with: 
            fetch-depth: 0
        - name: Semantic release
          uses: ./
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with: 
            dry_run: true
            extra_plugins: |
                @semantic-release/changelog@6.0.0
                @semantic-release/git